### ISSUE TITLE
Error when run iCloudDriveFuse.py

### ISSUE THREAD

**Issue by beckietech** [ixs/iCloudDriveFuse#1]
python3 iCloudDriveFuse.py 
Traceback (most recent call last):
  File "iCloudDriveFuse.py", line 31, in <module>
    from cachetools import TTLCache
ImportError: No module named 'cachetools'

Can I know the correct install/usage? Thanks!

**Comment by ixs** [comment]
you are missing the cachetools python module.

`pip install --user cachetools` should do the trick.

**Comment by beckietech** [comment]
thank you for the hint, after successfully installed, I got another message:
python3 iCloudDriveFuse.py 
Traceback (most recent call last):
  File "iCloudDriveFuse.py", line 32, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ImportError: No module named 'fuse'

UPDATE: I managed to install fuse by install pyfuse and the message becomes:
sudo python3 iCloudDriveFuse.py  .netrc
Traceback (most recent call last):
  File "iCloudDriveFuse.py", line 32, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
  File "/root/.local/lib/python3.5/site-packages/fuse/__init__.py", line 3, in <module>
    from .defect_augment import DefectAugment
  File "/root/.local/lib/python3.5/site-packages/fuse/defect_augment.py", line 11, in <module>
    from gunpowder import BatchFilter
  File "/root/.local/lib/python3.5/site-packages/gunpowder/__init__.py", line 3, in <module>
    from . import nodes
  File "/root/.local/lib/python3.5/site-packages/gunpowder/nodes/__init__.py", line 3, in <module>
    from .add_affinities import AddAffinities
  File "/root/.local/lib/python3.5/site-packages/gunpowder/nodes/add_affinities.py", line 4, in <module>
    from .batch_filter import BatchFilter
  File "/root/.local/lib/python3.5/site-packages/gunpowder/nodes/batch_filter.py", line 19
    return f"Error in {self.batch_filter.name()}: {self.msg}"

I looked up the readme but can't find which argument missing, can you please help? Thanks

**Comment by Lantizia** [comment]
I'm also getting a similar issue related to gunpowder...

```
Traceback (most recent call last):
  File "./iCloudDriveFuse.py", line 32, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
  File "/home/lantizia/.local/lib/python2.7/site-packages/fuse/__init__.py", line 3, in <module>
    from .defect_augment import DefectAugment
  File "/home/lantizia/.local/lib/python2.7/site-packages/fuse/defect_augment.py", line 11, in <module>
    from gunpowder import BatchFilter
  File "/home/lantizia/.local/lib/python2.7/site-packages/gunpowder/__init__.py", line 3, in <module>
    from . import nodes
  File "/home/lantizia/.local/lib/python2.7/site-packages/gunpowder/nodes/__init__.py", line 3, in <module>
    from .add_affinities import AddAffinities
  File "/home/lantizia/.local/lib/python2.7/site-packages/gunpowder/nodes/add_affinities.py", line 64
    f"AddAffinities works only in 2 or 3 dimensions, not {dims}")
                                                               ^
SyntaxError: invalid syntax
```

Only in my case I've been tested this on a very OLD copy of Ubuntu 18.04, mostly because 24.04 now lacks Python 2 support.

It'd be great if this application could be updated to work with Python 3... if I try to run it on Ubuntu 24.04 (and change the shebang to say python3 instead of just python) then I get things like...

```
Traceback (most recent call last):
  File "/home/stevenm/Downloads/iCloudDriveFuse-master/./iCloudDriveFuse.py", line 32, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ImportError: cannot import name 'FUSE' from 'fuse' (/usr/lib/python3/dist-packages/fuse.py). Did you mean: 'Fuse'?
```

And if I change 'FUSE' to 'Fuse' I then get...

```
Traceback (most recent call last):
  File "/home/stevenm/Downloads/iCloudDriveFuse-master/./iCloudDriveFuse.py", line 32, in <module>
    from fuse import Fuse, FuseOSError, Operations, LoggingMixIn
ImportError: cannot import name 'FuseOSError' from 'fuse' (/usr/lib/python3/dist-packages/fuse.py). Did you mean: 'FuseError'?

```
And if I change 'FuseOSError' to 'FuseError' I then get...

```
Traceback (most recent call last):
  File "/home/stevenm/Downloads/iCloudDriveFuse-master/./iCloudDriveFuse.py", line 32, in <module>
    from fuse import Fuse, FuseError, Operations, LoggingMixIn
ImportError: cannot import name 'Operations' from 'fuse' (/usr/lib/python3/dist-packages/fuse.py)
```

etc... etc... so who knows how many changes.

It would be brilliant to have a way of mounting iCloud Drive using FUSE on Linux.
